//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNote.Utils {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Hedefler : global::System.Configuration.ApplicationSettingsBase {
        
        private static Hedefler defaultInstance = ((Hedefler)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Hedefler())));
        
        public static Hedefler Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public double DailyPurchaseKREDİ_KARTI {
            get {
                return ((double)(this["DailyPurchaseKREDİ_KARTI"]));
            }
            set {
                this["DailyPurchaseKREDİ_KARTI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public double DailyPurchaseÇEK {
            get {
                return ((double)(this["DailyPurchaseÇEK"]));
            }
            set {
                this["DailyPurchaseÇEK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public double DailyPurchaseSENET {
            get {
                return ((double)(this["DailyPurchaseSENET"]));
            }
            set {
                this["DailyPurchaseSENET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public double DailyPurchaseNAKİT {
            get {
                return ((double)(this["DailyPurchaseNAKİT"]));
            }
            set {
                this["DailyPurchaseNAKİT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public double DailySalesKREDİ_KARTI {
            get {
                return ((double)(this["DailySalesKREDİ_KARTI"]));
            }
            set {
                this["DailySalesKREDİ_KARTI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public double DailySalesÇEK {
            get {
                return ((double)(this["DailySalesÇEK"]));
            }
            set {
                this["DailySalesÇEK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public double DailySalesSENET {
            get {
                return ((double)(this["DailySalesSENET"]));
            }
            set {
                this["DailySalesSENET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public double DailySalesNAKİT {
            get {
                return ((double)(this["DailySalesNAKİT"]));
            }
            set {
                this["DailySalesNAKİT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public double MonthlyAnalysisNET_DEĞER {
            get {
                return ((double)(this["MonthlyAnalysisNET_DEĞER"]));
            }
            set {
                this["MonthlyAnalysisNET_DEĞER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public double MonthlyAnalysisKAZANÇ {
            get {
                return ((double)(this["MonthlyAnalysisKAZANÇ"]));
            }
            set {
                this["MonthlyAnalysisKAZANÇ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public double MonthlyAnalysisHARCAMA {
            get {
                return ((double)(this["MonthlyAnalysisHARCAMA"]));
            }
            set {
                this["MonthlyAnalysisHARCAMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public double YearlyAnalysisNET_DEĞER {
            get {
                return ((double)(this["YearlyAnalysisNET_DEĞER"]));
            }
            set {
                this["YearlyAnalysisNET_DEĞER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public double YearlyAnalysisKAZANÇ {
            get {
                return ((double)(this["YearlyAnalysisKAZANÇ"]));
            }
            set {
                this["YearlyAnalysisKAZANÇ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public double YearlyAnalysisHARCAMA {
            get {
                return ((double)(this["YearlyAnalysisHARCAMA"]));
            }
            set {
                this["YearlyAnalysisHARCAMA"] = value;
            }
        }
    }
}
