//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNote.Utils {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class PrintingRoute : global::System.Configuration.ApplicationSettingsBase {
        
        private static PrintingRoute defaultInstance = ((PrintingRoute)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PrintingRoute())));
        
        public static PrintingRoute Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainGrid {
            get {
                return ((string)(this["MainGrid"]));
            }
            set {
                this["MainGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DailySales {
            get {
                return ((string)(this["DailySales"]));
            }
            set {
                this["DailySales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DailyPurchase {
            get {
                return ((string)(this["DailyPurchase"]));
            }
            set {
                this["DailyPurchase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MontlySales {
            get {
                return ((string)(this["MontlySales"]));
            }
            set {
                this["MontlySales"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MontlyPurchase {
            get {
                return ((string)(this["MontlyPurchase"]));
            }
            set {
                this["MontlyPurchase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Stok {
            get {
                return ((string)(this["Stok"]));
            }
            set {
                this["Stok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnalysisMontly {
            get {
                return ((string)(this["AnalysisMontly"]));
            }
            set {
                this["AnalysisMontly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnalysisYearly {
            get {
                return ((string)(this["AnalysisYearly"]));
            }
            set {
                this["AnalysisYearly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnalysisSalesman {
            get {
                return ((string)(this["AnalysisSalesman"]));
            }
            set {
                this["AnalysisSalesman"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AnalysisPotansial {
            get {
                return ((string)(this["AnalysisPotansial"]));
            }
            set {
                this["AnalysisPotansial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tür {
            get {
                return ((string)(this["Tür"]));
            }
            set {
                this["Tür"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Satış_Görevli {
            get {
                return ((string)(this["Satış_Görevli"]));
            }
            set {
                this["Satış_Görevli"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Kullanıcılar {
            get {
                return ((string)(this["Kullanıcılar"]));
            }
            set {
                this["Kullanıcılar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Firmalar {
            get {
                return ((string)(this["Firmalar"]));
            }
            set {
                this["Firmalar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Müşteriler {
            get {
                return ((string)(this["Müşteriler"]));
            }
            set {
                this["Müşteriler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Dosya_Takip {
            get {
                return ((string)(this["Dosya_Takip"]));
            }
            set {
                this["Dosya_Takip"] = value;
            }
        }
    }
}
