//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarNote.Utils {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class PrintingRoute : global::System.Configuration.ApplicationSettingsBase {
        
        private static PrintingRoute defaultInstance = ((PrintingRoute)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PrintingRoute())));
        
        public static PrintingRoute Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Adliye {
            get {
                return ((string)(this["Adliye"]));
            }
            set {
                this["Adliye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Özel {
            get {
                return ((string)(this["Özel"]));
            }
            set {
                this["Özel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Firma {
            get {
                return ((string)(this["Firma"]));
            }
            set {
                this["Firma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Harcama {
            get {
                return ((string)(this["Harcama"]));
            }
            set {
                this["Harcama"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Dosyalar {
            get {
                return ((string)(this["Dosyalar"]));
            }
            set {
                this["Dosyalar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Diller {
            get {
                return ((string)(this["Diller"]));
            }
            set {
                this["Diller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Hatırlatmalar {
            get {
                return ((string)(this["Hatırlatmalar"]));
            }
            set {
                this["Hatırlatmalar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Eskihatırlatmalar {
            get {
                return ((string)(this["Eskihatırlatmalar"]));
            }
            set {
                this["Eskihatırlatmalar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string günlükgider {
            get {
                return ((string)(this["günlükgider"]));
            }
            set {
                this["günlükgider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string günlükgelir {
            get {
                return ((string)(this["günlükgelir"]));
            }
            set {
                this["günlükgelir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string aylıkgider {
            get {
                return ((string)(this["aylıkgider"]));
            }
            set {
                this["aylıkgider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string aylıkgelir {
            get {
                return ((string)(this["aylıkgelir"]));
            }
            set {
                this["aylıkgelir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string aylıkişanaliz {
            get {
                return ((string)(this["aylıkişanaliz"]));
            }
            set {
                this["aylıkişanaliz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string yıllıkizanaliz {
            get {
                return ((string)(this["yıllıkizanaliz"]));
            }
            set {
                this["yıllıkizanaliz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tercümananaliz {
            get {
                return ((string)(this["tercümananaliz"]));
            }
            set {
                this["tercümananaliz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tercümanlar {
            get {
                return ((string)(this["tercümanlar"]));
            }
            set {
                this["tercümanlar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string adliyeler {
            get {
                return ((string)(this["adliyeler"]));
            }
            set {
                this["adliyeler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mahkemeler {
            get {
                return ((string)(this["mahkemeler"]));
            }
            set {
                this["mahkemeler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tanımlısirketler {
            get {
                return ((string)(this["tanımlısirketler"]));
            }
            set {
                this["tanımlısirketler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tanımlımüsteriter {
            get {
                return ((string)(this["tanımlımüsteriter"]));
            }
            set {
                this["tanımlımüsteriter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string belgeler {
            get {
                return ((string)(this["belgeler"]));
            }
            set {
                this["belgeler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string kullanıcılar {
            get {
                return ((string)(this["kullanıcılar"]));
            }
            set {
                this["kullanıcılar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Filemanagement {
            get {
                return ((string)(this["Filemanagement"]));
            }
            set {
                this["Filemanagement"] = value;
            }
        }
    }
}
